web: python src/manage.py migrate --noinput && python src/manage.py collectstatic --noinput && gunicorn --chdir src src.wsgi:application --log-file -
worker: cd src && celery -A src worker -l info
beat: cd src && celery -A src beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
