@startuml Medical_Appointment_System_Component
title Medical Appointment System - Component Diagram

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!ROUNDED_STYLE=1
LAYOUT_LEFT_RIGHT()
LAYOUT_TOP_DOWN()


System_Boundary(system, "Medical Appointment System") {
    Container(ui, "Web UI", "React / HTML / CSS / JavaScript", "Single Page Application that interacts with backend REST APIs")

    Container_Boundary(backend, "Backend"){
        'auth - patient: trạng'
        Component(auth_api, "Authentication API", "Django REST", "Provides authentication and authorization APIs")
        Component(patient_api, "Patient Profile API", "Django REST", "Provides APIs to manage patient personal information and medical history")

        'appointment - schedule: thuận'
        Component(appointment_api, "Appointment API", "Django REST", "Provides APIs to book, cancel and view medical appointments")
        Component(schedule_api, "Schedule API", "Django REST", "Provides APIs to manage and view doctor schedules")

        'admin - medical: trang'
        Component(medical_api, "Medical Record API", "Django REST" ,"Provides APIs to manage medical records and diagnosis information")
        Component(admin_api, "Doctor & Specialty Management API", "Django REST", "Provides APIs to manage doctors and medical specialties")
        
        'message - notification: trang'
        Component(message_producer, "Message Producer", "Celery Client", "Publishes events for asynchronous processing")
        Component(notification_worker, "Notification Worker", "Celery Worker", "Processes background tasks such as sending notifications")
        
    }
    'database: trạng'
    ContainerDb(database, "Relational Database", "MySQL", "Stores users, doctor schedules, appointments, medical records, and system configuration.")
}

'message queue: trang'
System_Ext(message_queue, "Message Queue (RabbitMQ)", "Delivers messages for asynchronous communication")
System_Ext(email_service, "Email Service", "Sends email notifications to users")

' auth - patient: trạng '
Rel(ui, auth_api, "Authenticates users", "HTTPS / JSON")
Rel(ui, patient_api, "Manages patient profile", "HTTPS / JSON")

' appointment - schedule: thuận'
Rel(ui, appointment_api, "Manages appointments", "HTTPS / JSON")
Rel(ui, schedule_api, "Views doctor schedules", "HTTPS / JSON")
Rel(appointment_api, schedule_api, "Checks doctor availability")

' admin - medical: trang'
Rel(ui, medical_api, "View medical records", "HTTPS / JSON")
Rel(ui, admin_api, "Manages doctors and specialties", "HTTPS / JSON")

' Asynchoronous Comunication: trang'
Rel(appointment_api, message_producer, "Publishes appointment events (confirmation, reminder)")
Rel(message_producer, message_queue, "Sends messages", "AMQP")
Rel(notification_worker, message_queue, "Delivers messages", "AMQP")
Rel(notification_worker, email_service, "Sends notification emails")

' database: trạng'
Rel(auth_api, database, "Reads/Writes authentication data")
Rel(patient_api, database, "Reads/Writes patient profile data")
Rel(appointment_api, database, "Reads/Writes appointment data")
Rel(schedule_api, database, "Reads/Writes schedule data")
Rel(medical_api, database, "Reads/Writes medical record data")
Rel(admin_api, database, "Reads/Writes doctor and specialty data")

@enduml